apiVersion: v1
kind: Secret
metadata:
  name: !service-VERSION!
  namespace: !service-ENV_NAME!
  labels:
    app: !service!
    ver: !BUILD_VERSION!
#    eg., R17_3_211, R17_3_212
#    isLive: "true"
#    stage: live
#     eg., live+1, live, live-1, live-2, live-3
#    feature: BRANCH_NAME
#    datetime: "DATE-TIME"
#    eg., 20170308225301
type: Opaque
data:
secrets.properties: !SECRET_PROPS!